"""
Design tokens for modern SaaS-style UI (CustomTkinter).
Single palette: primary, neutral, semantic. Typography and spacing scale.
"""

# --- Colors ---
# Primary: main actions, active nav
PRIMARY = "#2563EB"
PRIMARY_HOVER = "#1D4ED8"

# Neutral: sidebar, cards, text
NEUTRAL_BG_SIDEBAR = "#F8FAFC"
NEUTRAL_BG_CARD = "#FFFFFF"
NEUTRAL_BORDER = "#E2E8F0"
NEUTRAL_TEXT = "#1E293B"
NEUTRAL_TEXT_SECONDARY = "#64748B"
NEUTRAL_TEXT_MUTED = "#94A3B8"

# Semantic
SEMANTIC_SUCCESS = "#059669"
SEMANTIC_SUCCESS_HOVER = "#047857"
SEMANTIC_WARNING = "#D97706"
SEMANTIC_WARNING_HOVER = "#B45309"
SEMANTIC_ERROR = "#DC2626"
SEMANTIC_ERROR_HOVER = "#B91C1C"
SEMANTIC_INFO = "#0284C7"

# Chat tags (from palette)
CHAT_USER = "#1D4ED8"
CHAT_BOT = "#059669"
CHAT_TOOL = "#7C3AED"
CHAT_ERROR = "#DC2626"
CHAT_DEFAULT = "#1E293B"

# Connection status
STATUS_OK = SEMANTIC_SUCCESS
STATUS_ERROR = SEMANTIC_ERROR
STATUS_PENDING = SEMANTIC_WARNING

# --- Typography (CTkFont size) ---
FONT_HEADING = 20
FONT_SUBHEADING = 15
FONT_BODY = 14
FONT_LABEL = 13
FONT_CAPTION = 12
FONT_MONO = 11

# --- Spacing (px) ---
SPACE_UNIT = 8
SPACE_SM = SPACE_UNIT
SPACE_MD = SPACE_UNIT * 2
SPACE_LG = SPACE_UNIT * 3

# --- Components ---
CORNER_RADIUS = 8
BUTTON_HEIGHT_PRIMARY = 40
BUTTON_HEIGHT_SECONDARY = 36
SIDEBAR_WIDTH = 220
